### ISSUE TITLE
Nautilus closes when I type from keyboard (cont'd)

### ISSUE THREAD

**Issue by zappelin** [jaybosamiya/nautilus-interactive-typeahead-debian#6]
@vathe83 reported this issue but it was closed. 
Unfortunately, I managed to reproduce it. Specs:
- OS: Debian 10 (buster)
- GNOME nautilus 3.30.5
- Typeahead is ticked and I killed/restarted nautilus

I get the same result both with the quick install and building it myself. 

Happy to hear your thoughts, thanks 8-)

**Comment by vathe83** [comment]
It seems the same response as in my case but unfortunately I uninstalled it so I cannot help on that

**Comment by vathe83** [comment]
It seems the same response as in my case but unfortunately I uninstalled it so I cannot help on that

**Comment by vathe83** [comment]
It seems the same response as in my case but unfortunately I uninstalled it so I cannot help on that !

**Comment by vathe83** [comment]
It seems the same response as in my case but unfortunately I uninstalled it so I cannot help on that !

**Comment by vathe83** [comment]
It seems the same response as in my case but unfortunately I uninstalled it so I cannot help on that !

**Comment by jaybosamiya** [comment]
I use this version of Nautilus as my daily driver on Debian Buster and still haven't faced this issue. Without further details, I cannot reproduce this and thus do not know how to work on fixing it. Sorry.

**Comment by michaelfgeiger** [comment]
It works fine in folder view, but crashes in list view.
G_DEBUG="all" NAUTILUS_DEBUG="All" nautilus
Gdk-Message: Window 0xfoo is a temporary window without parent, application will not be able to position it on screen.
