### ISSUE TITLE
Installation with deb files not working

### ISSUE THREAD

**Issue by Tesla-Renting** [jaybosamiya/nautilus-interactive-typeahead-debian#7]
I am trying to install directly with the deb files from the debs folder.
### Steps to reproduce

-  `git clone https://github.com/jaybosamiya/nautilus-interactive-typeahead-debian.git`
- `cd nautilus-interactive-typeahead-debian`
- `sudo dpkg -i *.deb`
- `gsettings set org.gnome.nautilus.preferences enable-interactive-search true`
- restart
- start nautilus
- start typing

### Result
Nautilus crashes after the first letter. Nautilus crashes only if there is actually a folder that starts with that letter. Starting nautilus in terminal gives hint `Segmentation fault`:
```
Gdk-Message: 21:21:03.165: Window 0x5566f53bfb10 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 21:21:03.166: Window 0x5566f53bfb10 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 21:21:10.472: Window 0x5566f53bfb10 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 21:21:10.472: Window 0x5566f53bfb10 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 21:21:10.475: Window 0x5566f53bfb10 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 21:21:10.475: Window 0x5566f53bfb10 is a temporary window without parent, application will not be able to position it on screen.
Segmentation fault
```

### Specs

- nautilus version 3.30.5-stable (`nautilus --version` => `GNOME nautilus 3.30.5`)
- `cat /etc/debian_version` => `10.10`

**Comment by jaybosamiya** [comment]
Thanks for the detailed report, but unfortunately I have no idea why it crashes. I am currently using (and have been using for almost 2 years) the exact binaries on the exact same version of Debian and it works fine for me, so I cannot reproduce the issue.
